-- 简化的MySQL建表语句 - 只有用户表
CREATE DATABASE IF NOT EXISTS myprogram CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE myprogram;

-- 用户表
DROP TABLE IF EXISTS users;
CREATE TABLE users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL,
    age INT,
    city VARCHAR(50),
    balance DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;